<?php

namespace Proxies\__CG__\MyApp\HotelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chambre extends \MyApp\HotelBundle\Entity\Chambre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'idChambre', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'nbrePlace', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'prix', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'disponible', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'idHotel'];
        }

        return ['__isInitialized__', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'idChambre', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'nbrePlace', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'prix', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'disponible', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Chambre' . "\0" . 'idHotel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Chambre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdChambre()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdChambre();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdChambre', []);

        return parent::getIdChambre();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdChambre($idChambre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdChambre', [$idChambre]);

        return parent::setIdChambre($idChambre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrePlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrePlace', []);

        return parent::getNbrePlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrePlace($nbrePlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrePlace', [$nbrePlace]);

        return parent::setNbrePlace($nbrePlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function isDisponible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDisponible', []);

        return parent::isDisponible();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponible($disponible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponible', [$disponible]);

        return parent::setDisponible($disponible);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdHotel', []);

        return parent::getIdHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdHotel($idHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdHotel', [$idHotel]);

        return parent::setIdHotel($idHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponible', []);

        return parent::getDisponible();
    }

}
