<?php

namespace Proxies\__CG__\MyApp\HotelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \MyApp\HotelBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'idClient', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'prenom', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'login', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'pwd', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'photo', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'etat', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'idAdmin', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'idForum'];
        }

        return ['__isInitialized__', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'idClient', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'prenom', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'login', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'pwd', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'photo', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'etat', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'idAdmin', '' . "\0" . 'MyApp\\HotelBundle\\Entity\\Client' . "\0" . 'idForum'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdClient()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdClient();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdClient', []);

        return parent::getIdClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdClient($idClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdClient', [$idClient]);

        return parent::setIdClient($idClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', []);

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', [$login]);

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getPwd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPwd', []);

        return parent::getPwd();
    }

    /**
     * {@inheritDoc}
     */
    public function setPwd($pwd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPwd', [$pwd]);

        return parent::setPwd($pwd);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function isEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEtat', []);

        return parent::isEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAdmin', []);

        return parent::getIdAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAdmin($idAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAdmin', [$idAdmin]);

        return parent::setIdAdmin($idAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdForum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdForum', []);

        return parent::getIdForum();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdForum($idForum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdForum', [$idForum]);

        return parent::setIdForum($idForum);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

}
